---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-registration"
      label: "Registration"
      solveButton: false
    - name: "02-insights-login"
      label: "Insights Login"
      solveButton: false
    - name: "03-navigation"
      label: "Navigation"
      solveButton: false
    - name: "04-review"
      label: "Review"
      solveButton: false
    - name: "05-remediation"
      label: "Remediation"
      solveButton: false
    - name: "06-verify"
      label: "Verify"
      solveButton: false

tabs:
  - name: ">_ terminal"
    url: /wetty_rhel/ssh/root
  - name: "Red Hat Hybrid Cloud Console"
    url: https://console.redhat.com
    external: true
