In most Red Hat Enterprise Linux 9 installations, the insights-client
software will be installed by default. However, the minimal package set
does not include installing the insights-client package and other
versions of Red Hat Enterprise Linux, while the package is available,
will likely need it installed. Install the insights-client package on
the system.

[source,bash,run]
----
dnf -y install insights-client
----

Next, register your system with Red Hat Insights.

[source,bash,run]
----
insights-client --register
----

From the above output, you can observe that the system has been
successfully registered with Red Hat Insights. As part of the
registration, the machine also uploads a report to Red Hat Insights so
that it may be analyzed for any issues.

For future reference, make note of your system hostname.

[source,bash,run]
----
hostname
----

____
_NOTE:_ Your hostname will be different than the one listed in the
output above
____

At any time in the future, you can get information about Insights
registration by using the `+--status+` option to `+insights-client+`.

[source,bash,run]
----
insights-client --status
----
